In [1]:
#Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("train.csv")
df.shape

(1460, 81)

In [4]:
pd.set_option('display.max_rows',None)
pd.set_option("display.max_columns",None)

In [6]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [8]:
missing_value_clm_gre_20 = ['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']
df2 = df.drop(columns=missing_value_clm_gre_20)
df2.shape

(1460, 76)

In [10]:
df3=df2.select_dtypes(include=['int64',"float64"])
df3.shape

(1460, 38)

In [12]:
df3.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [15]:
num_var_miss=['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
df3[num_var_miss][df3[num_var_miss].isnull().any(axis=1)]

      LotFrontage  MasVnrArea  GarageYrBlt
7             NaN       240.0       1973.0
12            NaN         0.0       1962.0
14            NaN       212.0       1960.0
16            NaN       180.0       1970.0
24            NaN         0.0       1968.0
31            NaN         0.0       1966.0
39           65.0         0.0          NaN
42            NaN         0.0       1983.0
43            NaN         0.0       1977.0
48           33.0         0.0          NaN
50            NaN         0.0       1997.0
64            NaN       573.0       1998.0
66            NaN       287.0       1970.0
76            NaN         0.0       1956.0
78           72.0         0.0          NaN
84            NaN        22.0       1995.0
88          105.0         0.0          NaN
89           60.0         0.0          NaN
95            NaN        68.0       1993.0
99           77.0         0.0          NaN
100           NaN        28.0       1977.0
104           NaN       600.0       1951.0
108          85.0         0.0          NaN
111           NaN         0.0       2000.0
113           NaN       184.0       1953.0
116           NaN       116.0       1962.0
120           NaN         0.0       1969.0
125          60.0         0.0          NaN
126           NaN         0.0       1977.0
127          55.0         0.0          NaN
131           NaN        40.0       2000.0
133           NaN       136.0       2001.0
136           NaN       196.0       1967.0
140          70.0         0.0          NaN
147           NaN       180.0       2001.0
148          63.0       120.0          NaN
149           NaN         0.0       1936.0
152           NaN       252.0       1971.0
153           NaN         0.0       1960.0
155          60.0         0.0          NaN
160           NaN         0.0       1984.0
163          55.0         0.0          NaN
165          62.0         0.0          NaN
166           NaN         0.0       1955.0
169           NaN       653.0       1981.0
170           NaN         0.0       1991.0
177           NaN         0.0       1958.0
180           NaN       456.0       2000.0
186           NaN         0.0       1990.0
191           NaN       138.0       1972.0
198          92.0         0.0          NaN
203           NaN       205.0       2004.0
207           NaN         0.0       1960.0
208           NaN       128.0       1988.0
210          67.0         0.0          NaN
214           NaN       153.0       1977.0
218           NaN       312.0       1939.0
221           NaN         0.0       2002.0
234           NaN         NaN       2002.0
237           NaN         0.0       1993.0
241          40.0         0.0          NaN
244           NaN         0.0       1994.0
249           NaN       472.0       1958.0
250          55.0         0.0          NaN
269           NaN       174.0       1987.0
287           NaN         0.0          NaN
288           NaN        31.0       1970.0
291          55.0         0.0          NaN
293           NaN        34.0       1977.0
307           NaN         0.0          NaN
308           NaN         0.0       1961.0
310           NaN       112.0       1993.0
319           NaN       225.0       1980.0
328           NaN         0.0       1930.0
330           NaN        84.0       2002.0
335           NaN         0.0       1965.0
342           NaN       340.0       1949.0
346           NaN         0.0       1960.0
347           NaN        30.0       1960.0
351           NaN         0.0       1986.0
356           NaN       106.0       1992.0
360           NaN         0.0       1978.0
361           NaN         0.0       1940.0
364           NaN       120.0       1976.0
366           NaN       247.0       1963.0
369           NaN         0.0       1997.0
370           NaN         0.0       2000.0
375           NaN         0.0          NaN
384           NaN         0.0       1992.0
386          58.0         0.0          NaN
392           NaN         0.0       1959.0
393           NaN         0.0          NaN
404           NaN         0.0       1995.0
405           NaN         0.0       1993.0
412           NaN       432.0       2009.0
421           NaN       126.0       1977.0
426           NaN       145.0       1989.0
431          60.0         0.0          NaN
434          21.0         0.0          NaN
441          92.0       270.0          NaN
447           NaN         0.0       1998.0
452           NaN        42.0       1996.0
457           NaN         0.0       1954.0
458           NaN         0.0       1925.0
459           NaN       161.0       1950.0
464          60.0       136.0          NaN
465           NaN        18.0       2004.0
470           NaN         0.0       1985.0
484           NaN         0.0       1963.0
490           NaN         0.0       1976.0
495          60.0         0.0          NaN
496           NaN         0.0       1992.0
516           NaN       333.0       1972.0
518           NaN         0.0       1998.0
520          60.0         0.0          NaN
528          58.0         0.0          NaN
529           NaN         NaN       1975.0
533          50.0         0.0          NaN
535          70.0         0.0          NaN
537           NaN         0.0       1980.0
538           NaN       188.0       1968.0
539           NaN       479.0       2001.0
541           NaN        72.0       2000.0
545           NaN       178.0       1988.0
559           NaN        18.0       2003.0
560           NaN       180.0       1957.0
562          63.0         0.0          NaN
564           NaN         0.0       1992.0
569           NaN         0.0       1979.0
580           NaN        85.0       1960.0
582          81.0       104.0          NaN
593           NaN       170.0       2003.0
610           NaN       204.0       2000.0
611           NaN       233.0       1978.0
612           NaN       108.0       2001.0
613          70.0         0.0          NaN
614          21.0         0.0          NaN
616           NaN         0.0       2002.0
620          45.0         0.0          NaN
623           NaN       513.0       2000.0
626           NaN         0.0       1960.0
635          60.0         0.0          NaN
636          51.0         0.0          NaN
638          67.0         0.0          NaN
641           NaN         0.0       2001.0
645           NaN         0.0       1979.0
649          21.0         0.0          NaN
650          65.0         NaN       2007.0
660           NaN       233.0       1976.0
666           NaN       113.0       1965.0
668           NaN         0.0       1999.0
672           NaN         0.0       1977.0
679           NaN        57.0       1963.0
682           NaN         0.0       1996.0
685           NaN         0.0       1984.0
687           NaN         0.0       2004.0
690           NaN       147.0       2004.0
705          70.0         0.0          NaN
706           NaN       351.0       1971.0
709           NaN        41.0       1966.0
710          56.0         0.0          NaN
714           NaN       289.0       1976.0
720           NaN         0.0       1985.0
721           NaN       169.0       2004.0
726           NaN       260.0       1988.0
734           NaN         0.0       1968.0
738          60.0         0.0          NaN
745           NaN       289.0       1994.0
746           NaN         0.0       2000.0
750          55.0         0.0          NaN
751           NaN         0.0       2003.0
757           NaN       328.0       1978.0
770           NaN         0.0       1983.0
783           NaN       104.0       1978.0
784          35.0         0.0          NaN
785           NaN         0.0       1967.0
789           NaN       157.0       1966.0
791           NaN         0.0       1976.0
794           NaN         0.0       1994.0
811           NaN       169.0       2004.0
816           NaN         0.0       1954.0
817           NaN       148.0       2002.0
822           NaN         0.0       2003.0
826          50.0         0.0          NaN
828           NaN         0.0       1967.0
840           NaN         0.0       1934.0
843          80.0         0.0          NaN
845           NaN         0.0       1975.0
851           NaN        40.0       2003.0
853           NaN       115.0       1964.0
855           NaN         0.0       1962.0
856           NaN         0.0       1981.0
859           NaN       220.0       1968.0
865           NaN        76.0       1973.0
868           NaN         0.0       1979.0
879           NaN        90.0       1978.0
882           NaN         0.0       1993.0
893           NaN         0.0       1954.0
900           NaN         0.0       1979.0
904           NaN        75.0       1967.0
908           NaN         0.0       1983.0
911           NaN         0.0       1978.0
917           NaN         0.0       1956.0
921          67.0         0.0          NaN
925           NaN         0.0       1977.0
927           NaN       342.0       1968.0
928           NaN         0.0       2001.0
929           NaN       285.0       1997.0
936          67.0         NaN       2003.0
939           NaN         0.0       1940.0
941           NaN       298.0       1999.0
942          42.0         0.0          NaN
944           NaN       541.0       1958.0
953           NaN       232.0       1969.0
954          35.0       250.0          NaN
960          50.0         0.0          NaN
961           NaN       424.0       1977.0
967           NaN       151.0       1955.0
968          50.0         0.0          NaN
970          60.0         0.0          NaN
973          95.0         NaN       2007.0
975           NaN         0.0       2000.0
976          51.0         0.0          NaN
977          35.0         NaN       2007.0
980           NaN       210.0       1961.0
983           NaN         0.0       2002.0
988           NaN       298.0       1976.0
996           NaN         0.0       1961.0
997           NaN       571.0       1970.0
1003          NaN       164.0       1976.0
1006          NaN         0.0       1970.0
1009         60.0         0.0          NaN
1011         75.0         0.0          NaN
1017          NaN         0.0       1984.0
1018          NaN        76.0       1991.0
1024          NaN         0.0       1976.0
1030          NaN         0.0          NaN
1032          NaN         0.0       1993.0
1033          NaN       295.0       2002.0
1035          NaN         0.0       1957.0
1037          NaN       396.0       2001.0
1038         21.0         0.0          NaN
1041          NaN       252.0       1966.0
1045          NaN         0.0       1955.0
1057          NaN         0.0       1994.0
1059          NaN       480.0       1977.0
1064          NaN       200.0       1966.0
1077          NaN         0.0       1969.0
1084          NaN         0.0       1995.0
1086          NaN         0.0       1973.0
1096         60.0         0.0          NaN
1097          NaN         0.0       1987.0
1108          NaN         0.0       2000.0
1110          NaN         0.0       1995.0
1116          NaN         0.0       2002.0
1122          NaN         0.0       1956.0
1123         50.0         0.0          NaN
1124          NaN       170.0       1992.0
1131         63.0         0.0          NaN
1137         54.0         0.0          NaN
1138          NaN         0.0       1977.0
1141          NaN        44.0       1976.0
1143          NaN         0.0          NaN
1146          NaN        85.0       1985.0
1148          NaN         0.0       1982.0
1153          NaN         0.0       2002.0
1154          NaN       288.0       1965.0
1161          NaN        72.0       1993.0
1164          NaN         0.0       1978.0
1173        138.0         0.0          NaN
1177          NaN         0.0       1926.0
1179         77.0         0.0          NaN
1180          NaN         0.0       1990.0
1190          NaN       149.0       1975.0
1193          NaN       425.0       1999.0
1206          NaN         0.0       1966.0
1213          NaN         0.0       1965.0
1218         52.0         0.0          NaN
1219         21.0       236.0          NaN
1230          NaN         1.0       1977.0
1233          NaN       180.0       1959.0
1234         55.0         0.0          NaN
1243        107.0         NaN       2006.0
1244          NaN         0.0       1931.0
1247          NaN       335.0       1976.0
1251          NaN       163.0       2003.0
1253          NaN         0.0       1974.0
1257         56.0         0.0          NaN
1260          NaN         0.0       1999.0
1262          NaN         0.0       1957.0
1268          NaN       632.0       1982.0
1270          NaN         0.0       1979.0
1271          NaN         0.0       1968.0
1272          NaN       114.0       1965.0
1276          NaN         0.0       1972.0
1277          NaN       359.0       1967.0
1278         75.0         NaN       2002.0
1283         94.0         0.0          NaN
1286          NaN       451.0       1963.0
1287          NaN       621.0       1964.0
1290          NaN        86.0       1964.0
1300          NaN       344.0       1999.0
1301          NaN         0.0       1942.0
1309          NaN        88.0       1991.0
1312          NaN       336.0       1990.0
1318          NaN       178.0       2001.0
1321          NaN         0.0       1955.0
1323         50.0         0.0          NaN
1325         40.0         0.0          NaN
1326         70.0         0.0          NaN
1337        153.0         0.0          NaN
1342          NaN       149.0       2002.0
1346          NaN         0.0       1968.0
1348          NaN         0.0       1998.0
1349         50.0         0.0          NaN
1354          NaN         0.0       2000.0
1356          NaN        65.0       1966.0
1357          NaN         0.0       1971.0
1358          NaN       216.0       2000.0
1362          NaN         0.0       1920.0
1365          NaN         0.0       2000.0
1368          NaN       170.0       2003.0
1373          NaN       705.0       2001.0
1381          NaN         0.0       1970.0
1383          NaN         0.0       2007.0
1396          NaN         0.0       1966.0
1407          NaN         0.0          NaN
1417          NaN       731.0       1998.0
1419          NaN       312.0       1969.0
1423          NaN         0.0       1966.0
1424          NaN         0.0       1970.0
1429          NaN       310.0       1981.0
1431          NaN         0.0       1976.0
1441          NaN       147.0       2004.0
1443          NaN         0.0       1916.0
1446          NaN       189.0       1962.0
1449         21.0         0.0          NaN
1450         60.0         0.0          NaN
1453         90.0         0.0          NaN

In [18]:
df['LotConfig'].unique()

array(['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3'], dtype=object)