In [18]:
import numpy as np # linear algebra
import pandas as pd

In [19]:
df = pd.read_csv('papers.csv')
df.head(10)

,id,year,title,event_type,pdf_name,abstract,paper_text
0,1,1987,Self-Organization of Associative Database and ...,NaN,1-self-organization-of-associative-database-an...,Abstract Missing,767\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABA...
1,10,1987,A Mean Field Theory of Layer IV of Visual Cort...,NaN,10-a-mean-field-theory-of-layer-iv-of-visual-c...,Abstract Missing,683\n\nA MEAN FIELD THEORY OF LAYER IV OF VISU...
2,100,1988,Storing Covariance by the Associative Long-Ter...,NaN,100-storing-covariance-by-the-associative-long...,Abstract Missing,394\n\nSTORING COVARIANCE BY THE ASSOCIATIVE\n...
3,1000,1994,Bayesian Query Construction for Neural Network...,NaN,1000-bayesian-query-construction-for-neural-ne...,Abstract Missing,Bayesian Query Construction for Neural\nNetwor...
4,1001,1994,"Neural Network Ensembles, Cross Validation, an...",NaN,1001-neural-network-ensembles-cross-validation...,Abstract Missing,"Neural Network Ensembles, Cross\nValidation, a..."
5,1002,1994,Using a neural net to instantiate a deformable...,NaN,1002-using-a-neural-net-to-instantiate-a-defor...,Abstract Missing,U sing a neural net to instantiate a\ndeformab...
6,1003,1994,Plasticity-Mediated Competitive Learning,NaN,1003-plasticity-mediated-competitive-learning.pdf,Abstract Missing,Plasticity-Mediated Competitive Learning\n\nTe...
7,1004,1994,ICEG Morphology Classification using an Analog...,NaN,1004-iceg-morphology-classification-using-an-a...,Abstract Missing,ICEG Morphology Classification using an\nAnalo...
8,1005,1994,Real-Time Control of a Tokamak Plasma Using Ne...,NaN,1005-real-time-control-of-a-tokamak-plasma-usi...,Abstract Missing,Real-Time Control of a Tokamak Plasma\nUsing N...
9,1006,1994,Pulsestream Synapses with Non-Volatile Analogu...,NaN,1006-pulsestream-synapses-with-non-volatile-an...,Abstract Missing,Real-Time Control of a Tokamak Plasma\nUsing N...

In [20]:
df.shape

(7241, 7)

In [21]:
df.isnull().sum()

id               0
year             0
title            0
event_type    4819
pdf_name         0
abstract         0
paper_text       0
dtype: int64

In [22]:
df['paper_text']

0       767\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABA...
1       683\n\nA MEAN FIELD THEORY OF LAYER IV OF VISU...
2       394\n\nSTORING COVARIANCE BY THE ASSOCIATIVE\n...
3       Bayesian Query Construction for Neural\nNetwor...
4       Neural Network Ensembles, Cross\nValidation, a...
                              ...
7236    Single Transistor Learning Synapses\n\nPaul Ha...
7237    Bias, Variance and the Combination of\nLeast S...
7238    A Real Time Clustering CMOS\nNeural Engine\nT....
7239    Learning direction in global motion: two\nclas...
7240    Correlation and Interpolation Networks for\nRe...
Name: paper_text, Length: 7241, dtype: object

In [23]:
df['paper_text'][0]

'767\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABASE\nAND ITS APPLICATIONS\nHisashi Suzuki and Suguru Arimoto\nOsaka University, Toyonaka, Osaka 560, Japan\nABSTRACT\nAn efficient method of self-organizing associative databases is proposed together with\napplications to robot eyesight systems. The proposed databases can associate any input\nwith some output. In the first half part of discussion, an algorithm of self-organization is\nproposed. From an aspect of hardware, it produces a new style of neural network. In the\nlatter half part, an applicability to handwritten letter recognition and that to an autonomous\nmobile robot system are demonstrated.\n\nINTRODUCTION\nLet a mapping f : X -+ Y be given. Here, X is a finite or infinite set, and Y is another\nfinite or infinite set. A learning machine observes any set of pairs (x, y) sampled randomly\nfrom X x Y. (X x Y means the Cartesian product of X and Y.) And, it computes some\nestimate j : X -+ Y of f to make small, the estimation error in some measure.\nUsually we say that: the faster the decrease of estimation error with increase of the number of samples, the better the learning machine. However, such expression on performance\nis incomplete. Since, it lacks consideration on the candidates of J of j assumed preliminarily. Then, how should we find out good learning machines? To clarify this conception,\nlet us discuss for a while on some types of learning machines. And, let us advance the\nunderstanding of the self-organization of associative database .\n. Parameter Type\nAn ordinary type of learning machine assumes an equation relating x\'s and y\'s with\nparameters being indefinite, namely, a structure of f. It is equivalent to define implicitly a\nset F of candidates of\n(F is some subset of mappings from X to Y.) And, it computes\nvalues of the parameters based on the observed samples. We call such type a parameter\ntype.\nFor a learning machine defined well, if F 3 f, j approaches f as the number of samples\nincreases. In the alternative case, however, some estimation error remains eternally. Thus,\na problem of designing a learning machine returns to find out a proper structure of f in this\nsense.\nOn the other hand, the assumed structure of f is demanded to be as compact as possible\nto achieve a fast learning. In other words, the number of parameters should be small. Since,\nif the parameters are few, some j can be uniquely determined even though the observed\nsamples are few. However, this demand of being proper contradicts to that of being compact.\nConsequently, in the parameter type, the better the compactness of the assumed structure\nthat is proper, the better the learning machine. This is the most elementary conception\nwhen we design learning machines .\n\n1.\n\n. Universality and Ordinary Neural Networks\nNow suppose that a sufficient knowledge on f is given though J itself is unknown. In\nthis case, it is comparatively easy to find out proper and compact structures of J. In the\nalternative case, however, it is sometimes difficult. A possible solution is to give up the\ncompactness and assume an almighty structure that can cover various 1\'s. A combination\nof some orthogonal bases of the infinite dimension is such a structure. Neural networks 1 ,2\nare its approximations obtained by truncating finitely the dimension for implementation.\n\n? American Institute of Physics 1988\n\n\x0c768\nA main topic in designing neural networks is to establish such desirable structures of 1.\nThis work includes developing practical procedures that compute values of coefficients from\nthe observed samples. Such discussions are :flourishing since 1980 while many efficient methods have been proposed. Recently, even hardware units computing coefficients in parallel\nfor speed-up are sold, e.g., ANZA, Mark III, Odyssey and E-1.\nNevertheless, in neural networks, there always exists a danger of some error remaining\neternally in estimating /. Precisely speaking, suppose that a combination of the bases of a\nfinite number can define a structure of 1 essentially. In other words, suppose that F 3 /, or\n1 is located near F. In such case, the estimation error is none or negligible. However, if 1\nis distant from F, the estimation error never becomes negligible. Indeed, many researches\nreport that the following situation appears when 1 is too complex. Once the estimation\nerror converges to some value (> 0) as the number of samples increases, it decreases hardly\neven though the dimension is heighten. This property sometimes is a considerable defect of\nneural networks .\n. Recursi ve Type\nThe recursive type is founded on another methodology of learning that should be as\nfollows. At the initial stage of no sample, the set Fa (instead of notation F) of candidates\nof I equals to the set of all mappings from X to Y. After observing the first sample\n(Xl, Yl) E X x Y, Fa is reduced to Fi so that I(xt) = Yl for any I E F. After observing\nthe second sample (X2\' Y2) E X x Y, Fl is further reduced to F2 so that i(xt) = Yl and\nI(X2) = Y2 for any I E F. Thus, the candidate set F becomes gradually small as observation\nof samples proceeds. The after observing i-samples, which we write\nis one of the most\nlikelihood estimation of 1 selected in fi;. Hence, contrarily to the parameter type, the\nrecursive type guarantees surely that j approaches to 1 as the number of samples increases.\nThe recursive type, if observes a sample (x" yd, rewrites values 1,-l(X),S to I,(x)\'s for\nsome x\'s correlated to the sample. Hence, this type has an architecture composed of a rule\nfor rewriting and a free memory space. Such architecture forms naturally a kind of database\nthat builds up management systems of data in a self-organizing way. However, this database\ndiffers from ordinary ones in the following sense. It does not only record the samples already\nobserved, but computes some estimation of l(x) for any x E X. We call such database an\nassociative database.\nThe first subject in constructing associative databases is how we establish the rule for\nrewri ting. For this purpose, we adap t a measure called the dissimilari ty. Here, a dissimilari ty\nmeans a mapping d : X x X -+ {reals > O} such that for any (x, x) E X x X, d(x, x) > 0\nwhenever l(x) t /(x). However, it is not necessarily defined with a single formula. It is\ndefinable with, for example, a collection of rules written in forms of "if? .. then?? .. "\nThe dissimilarity d defines a structure of 1 locally in X x Y. Hence, even though\nthe knowledge on f is imperfect, we can re:flect it on d in some heuristic way. Hence,\ncontrarily to neural networks, it is possible to accelerate the speed of learning by establishing\nd well. Especially, we can easily find out simple d\'s for those l\'s which process analogically\ninformation like a human. (See the applications in this paper.) And, for such /\'s, the\nrecursive type shows strongly its effectiveness.\nWe denote a sequence of observed samples by (Xl, Yd, (X2\' Y2),???. One of the simplest\nconstructions of associative databases after observing i-samples (i = 1,2,.,,) is as follows.\n\ni\n\ni"\n\nI,\n\nAlgorithm 1. At the initial stage, let So be the empty set. For every i =\n1,2" .. , let i,-l(x) for any x E X equal some y* such that (x*,y*) E S,-l and\n\nd(x, x*) =\n\nmin\n(%,y)ES.-t\n\nd(x, x) .\n\nFurthermore, add (x" y,) to S;-l to produce Sa, i.e., S, = S,_l U {(x"\n\n(1)\n\ny,n.\n\n\x0c769\n\nAnother version improved to economize the memory is as follows.\n\nAlgorithm 2, At the initial stage, let So be composed of an arbitrary element\nin X x Y. For every i = 1,2"", let ii-lex) for any x E X equal some y. such\nthat (x?, y.) E Si-l and\nd(x, x?) =\n\nmin\n\nd(x, x) .\n\n(i,i)ES.-l\n\nFurthermore, if ii-l(Xi) # Yi then let Si = Si-l, or add (Xi, Yi) to Si-l to\nproduce Si, i.e., Si = Si-l U {(Xi, Yi)}\'\nIn either construction, ii approaches to f as i increases. However, the computation time\ngrows proportionally to the size of Si. The second subject in constructing associative\ndatabases is what addressing rule we should employ to economize the computation time. In\nthe subsequent chapters, a construction of associative database for this purpose is proposed.\nIt manages data in a form of binary tree.\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABASE\nGiven a sample sequence (Xl, Yl), (X2\' Y2), .. " the algorithm for constructing associative\ndatabase is as follows.\n\nAlgorithm 3,\'\n\nStep I(Initialization): Let (x[root], y[root]) = (Xl, Yd. Here, x[.] and y[.] are\nvariables assigned for respective nodes to memorize data.. Furthermore, let t = 1.\nStep 2: Increase t by 1, and put x, in. After reset a pointer n to the root, repeat\nthe following until n arrives at some terminal node, i.e., leaf.\nNotations nand\nd(xt, x[n)), let n\n\nn mean the descendant nodes of n.\n=n. Otherwise, let n =n.\n\nIf d(x" r[n)) ~\n\nStep 3: Display yIn] as the related information. Next, put y, in. If yIn] = y" back\nto step 2. Otherwise, first establish new descendant nodes n and n. Secondly,\nlet\n\n(x[n], yIn))\n(x[n], yIn))\n\n(x[n], yIn)),\n(Xt, y,).\n\n(2)\n(3)\n\nFinally, back to step 2. Here, the loop of step 2-3 can be stopped at any time\nand also can be continued.\nNow, suppose that gate elements, namely, artificial "synapses" that play the role of branching by d are prepared. Then, we obtain a new style of neural network with gate elements\nbeing randomly connected by this algorithm.\n\nLETTER RECOGNITION\nRecen tly, the vertical slitting method for recognizing typographic English letters3 , the\nelastic matching method for recognizing hand written discrete English letters4 , the global\ntraining and fuzzy logic search method for recognizing Chinese characters written in square\nstyleS, etc. are published. The self-organization of associative database realizes the recognition of handwritten continuous English letters.\n\n\x0c770\n\n9 /wn"\n\nNOV\n\n~ ~ ~ -xk :La.t\n\n~~ ~ ~~~\n\ndw1lo\'\n\n~~~~~of~~\n\n~~~ 4,-?~~4Fig. 1. Source document.\n2~~---------------\'\n\nlOO~---------------\'\n\nH\n\no\n\no\nFig. 2. Windowing.\n\n1000\n\n2000\n\n3000\n\n4000\n\nNumber of samples\n\no\n\n1000\n\n2000\n\n3000\n\n4000\n\nNUAlber of sampl es\n\nFig. 3. An experiment result.\n\nAn image scanner takes a document image (Fig. 1). The letter recognizer uses a parallelogram window that at least can cover the maximal letter (Fig. 2), and processes the\nsequence of letters while shifting the window. That is, the recognizer scans a word in a\nslant direction. And, it places the window so that its left vicinity may be on the first black\npoint detected. Then, the window catches a letter and some part of the succeeding letter.\nIf recognition of the head letter is performed, its end position, namely, the boundary line\nbetween two letters becomes known. Hence, by starting the scanning from this boundary\nand repeating the above operations, the recognizer accomplishes recursively the task. Thus\nthe major problem comes to identifying the head letter in the window.\nConsidering it, we define the following.\n? Regard window images as x\'s, and define X accordingly.\n? For a (x, x) E X x X, denote by B a black point in the left area from the boundary on\nwindow image X. Project each B onto window image x. Then, measure the Euclidean\ndistance 6 between fj and a black point B on x being the closest to B. Let d(x, x) be\nthe summation of 6\'s for all black points B\'s on x divided by the number of B\'s.\n? Regard couples of the "reading" and the position of boundary as y\'s, and define Y\naccordingly.\nAn operator teaches the recognizer in interaction the relation between window image and\nreading& boundary with algorithm 3. Precisely, if the recalled reading is incorrect, the\noperator teaches a correct reading via the console. Moreover, if the boundary position is\nincorrect, he teaches a correct position via the mouse.\nFig. 1 shows partially a document image used in this experiment. Fig. 3 shows the\nchange of the number of nodes and that of the recognition rate defined as the relative\nfrequency of correct answers in the past 1000 trials. Speciiications of the window are height\n= 20dot, width = 10dot, and slant angular = 68deg. In this example, the levels of tree\nwere distributed in 6-19 at time 4000 and the recognition rate converged to about 74%.\nExperimentally, the recognition rate converges to about 60-85% in most cases, and to 95% at\na rare case. However, it does not attain 100% since, e.g., "c" and "e" are not distinguishable\nbecause of excessive lluctuation in writing. If the consistency of the x, y-relation is not\nassured like this, the number of nodes increases endlessly (d. Fig. 3). Hence, it is clever to\nstop the learning when the recognition rate attains some upper limit. To improve further\nthe recognition rate, we must consider the spelling of words. It is one of future subjects.\n\n\x0c771\n\nOBSTACLE AVOIDING MOVEMENT\nVarious systems of camera type autonomous mobile robot are reported flourishingly6-1O.\nThe system made up by the authors (Fig. 4) also belongs to this category. Now, in mathematical methodologies, we solve usually the problem of obstacle avoiding movement as\na cost minimization problem under some cost criterion established artificially. Contrarily,\nthe self-organization of associative database reproduces faithfully the cost criterion of an\noperator. Therefore, motion of the robot after learning becomes very natural.\nNow, the length, width and height of the robot are all about O.7m, and the weight is\nabout 30kg. The visual angle of camera is about 55deg. The robot has the following three\nfactors of motion. It turns less than ?30deg, advances less than 1m, and controls speed less\nthan 3km/h. The experiment was done on the passageway of wid th 2.5m inside a building\nwhich the authors\' laboratories exist in (Fig. 5). Because of an experimental intention, we\narrange boxes, smoking stands, gas cylinders, stools, handcarts, etc. on the passage way at\nrandom. We let the robot take an image through the camera, recall a similar image, and\ntrace the route preliminarily recorded on it. For this purpose, we define the following.\n? Let the camera face 28deg downward to take an image, and process it through a low\npass filter. Scanning vertically the filtered image from the bottom to the top, search\nthe first point C where the luminance changes excessively. Then, su bstitu te all points\nfrom the bottom to C for white, and all points from C to the top for black (Fig. 6).\n(If no obstacle exists just in front of the robot, the white area shows the \'\'free\'\' area\nwhere the robot can move around.) Regard binary 32 x 32dot images processed thus\nas x\'s, and define X accordingly.\n? For every (x, x) E X x X, let d(x, x) be the number of black points on the exclusive-or\nimage between x and X.\n? Regard as y\'s the images obtained by drawing routes on images x\'s, and define Y\naccordingly.\nThe robot superimposes, on the current camera image x, the route recalled for x, and\ninquires the operator instructions. The operator judges subjectively whether the suggested\nroute is appropriate or not. In the negative answer, he draws a desirable route on x with the\nmouse to teach a new y to the robot. This opera.tion defines implicitly a sample sequence\nof (x, y) reflecting the cost criterion of the operator.\n\n.::l" !\n-\n\nIibUBe\n\n_. -\n\n22\n\n11\n\nRoan\n\n12\n\n{-\n\n13\n\nStationary uni t\n\nFig. 4. Configuration of\nautonomous mobile robot system.\n\n~\n\nI\n\n,\n\n23\n\n24\n\nNorth\n14\n\nrmbi Ie unit (robot)\n\n-\n\nRoan\n\ny\n\nt\n\nFig. 5. Experimental\nenvironment.\n\n\x0c772\n\nWall\n\nCamera image\n\nPreprocessing\n\nA\n\n::: !fa\n\n?\n\nPreprocessing\n\n0\n\nO\n\nCourse\nsuggest ion\n\n??\n\n..\n\nSearch\n\nA\n\nFig. 6. Processing for\nobstacle avoiding movement.\n\nx\n\nFig. 1. Processing for\nposition identification.\nWe define the satisfaction rate by the relative frequency of acceptable suggestions of\nroute in the past 100 trials. In a typical experiment, the change of satisfaction rate showed\na similar tendency to Fig. 3, and it attains about 95% around time 800. Here, notice that\nthe rest 5% does not mean directly the percentage of collision. (In practice, we prevent the\ncollision by adopting some supplementary measure.) At time 800, the number of nodes was\n145, and the levels of tree were distributed in 6-17.\nThe proposed method reflects delicately various characters of operator. For example, a\nrobot trained by an operator 0 moves slowly with enough space against obstacles while one\ntrained by another operator 0\' brushes quickly against obstacles. This fact gives us a hint\non a method of printing "characters" into machines.\nPOSITION IDENTIFICATION\nThe robot can identify its position by recalling a similar landscape with the position data\nto a camera image. For this purpose, in principle, it suffices to regard camera images and\nposition data as x\'s and y\'s, respectively. However, the memory capacity is finite in actual\ncompu ters. Hence, we cannot but compress the camera images at a slight loss of information.\nSuch compression is admittable as long as the precision of position identification is in an\nacceptable area. Thus, the major problem comes to find out some suitable compression\nmethod.\nIn the experimental environment (Fig. 5), juts are on the passageway at intervals of\n3.6m, and each section between adjacent juts has at most one door. The robot identifies\nroughly from a surrounding landscape which section itself places in. And, it uses temporarily\na triangular surveying technique if an exact measure is necessary. To realize the former task,\nwe define the following .\n? Turn the camera to take a panorama image of 360deg. Scanning horizontally the\ncenter line, substitute the points where the luminance excessively changes for black\nand the other points for white (Fig. 1). Regard binary 360dot line images processed\nthus as x\'s, and define X accordingly.\n? For every (x, x) E X x X, project each black point A on x onto x. And, measure the\nEuclidean distance 6 between A and a black point A on x being the closest to A. Let\nthe summation of 6 be S. Similarly, calculate S by exchanging the roles of x and X.\nDenoting the numbers of A\'s and A\'s respectively by nand n, define\n\n\x0c773\n\nd(x, x) =\n\n~(~\n+ ~).\n2 n\nn\n\n(4)\n\n? Regard positive integers labeled on sections as y\'s (cf. Fig. 5), and define Y accordingly.\nIn the learning mode, the robot checks exactly its position with a counter that is reset periodically by the operator. The robot runs arbitrarily on the passageways within 18m area\nand learns the relation between landscapes and position data. (Position identification beyond 18m area is achieved by crossing plural databases one another.) This task is automatic\nexcepting the periodic reset of counter, namely, it is a kind of learning without teacher.\nWe define the identification rate by the relative frequency of correct recalls of position\ndata in the past 100 trials. In a typical example, it converged to about 83% around time\n400. At time 400, the number of levels was 202, and the levels oftree were distributed in 522. Since the identification failures of 17% can be rejected by considering the trajectory, no\npro blem arises in practical use. In order to improve the identification rate, the compression\nratio of camera images must be loosened. Such possibility depends on improvement of the\nhardware in the future.\nFig. 8 shows an example of actual motion of the robot based on the database for obstacle\navoiding movement and that for position identification. This example corresponds to a case\nof moving from 14 to 23 in Fig. 5. Here, the time interval per frame is about 40sec.\n\n,~. .~ (\n;~"i..\n~\n\n"\n\n"\n\n.\n\n..I\n\nI\n\n?\n?\n\n"\n\nI\'\n.\n\'.1\nt\n\n;\n\ni\n\n-:\n, . . , \'II\n\nFig. 8. 

In [24]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer

In [25]:
stop_words = set(stopwords.words('english'))
new_stop_words = ["fig","figure","image","sample","using", 
             "show", "result", "large", 
             "also", "one", "two", "three", 
             "four", "five", "seven","eight","nine"]

In [26]:
stop_words = list(stop_words.union(new_stop_words))

In [27]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer

def preprocess_text(txt):
    # Lower case
    txt = txt.lower()
    # Remove HTML tags
    txt = re.sub(r"<.*?>", " ", txt)
    # Remove special characters and digits
    txt = re.sub(r"[^a-zA-Z]", " ", txt)
    # tokenization
    txt = nltk.word_tokenize(txt)
    # Remove stopwords
    txt = [word for word in txt if word not in stop_words]
    # Remove words less than three letters
    txt = [word for word in txt if len(word) >= 3]
    # Lemmatize
    lmtr = WordNetLemmatizer()
    txt = [lmtr.lemmatize(word) for word in txt]

    return " ".join(txt)

In [32]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')  # Optional: To get better support for lemmatization

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\antuk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\antuk\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [28]:
preprocess_text("HELO word loving moving the to from 99999 *&^ <p>This is a <b>sample</b> text with <i>HTML tags</i>.</p>")

'helo word loving moving text html tag'

In [29]:
import nltk

In [30]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\antuk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [33]:
docs = df['paper_text'].apply(lambda x:preprocess_text(x))

In [34]:
docs

0       self organization associative database applica...
1       mean field theory layer visual cortex applicat...
2       storing covariance associative long term poten...
3       bayesian query construction neural network mod...
4       neural network ensemble cross validation activ...
                              ...
7236    single transistor learning synapsis paul hasle...
7237    bias variance combination least square estimat...
7238    real time clustering cmos neural engine serran...
7239    learning direction global motion class psychop...
7240    correlation interpolation network real time ex...
Name: paper_text, Length: 7241, dtype: object

In [35]:
df

,id,year,title,event_type,pdf_name,abstract,paper_text
0,1,1987,Self-Organization of Associative Database and ...,NaN,1-self-organization-of-associative-database-an...,Abstract Missing,767\n\nSELF-ORGANIZATION OF ASSOCIATIVE DATABA...
1,10,1987,A Mean Field Theory of Layer IV of Visual Cort...,NaN,10-a-mean-field-theory-of-layer-iv-of-visual-c...,Abstract Missing,683\n\nA MEAN FIELD THEORY OF LAYER IV OF VISU...
2,100,1988,Storing Covariance by the Associative Long-Ter...,NaN,100-storing-covariance-by-the-associative-long...,Abstract Missing,394\n\nSTORING COVARIANCE BY THE ASSOCIATIVE\n...
3,1000,1994,Bayesian Query Construction for Neural Network...,NaN,1000-bayesian-query-construction-for-neural-ne...,Abstract Missing,Bayesian Query Construction for Neural\nNetwor...
4,1001,1994,"Neural Network Ensembles, Cross Validation, an...",NaN,1001-neural-network-ensembles-cross-validation...,Abstract Missing,"Neural Network Ensembles, Cross\nValidation, a..."
...,...,...,...,...,...,...,...
7236,994,1994,Single Transistor Learning Synapses,NaN,994-single-transistor-learning-synapses.pdf,Abstract Missing,Single Transistor Learning Synapses\n\nPaul Ha...
7237,996,1994,"Bias, Variance and the Combination of Least Sq...",NaN,996-bias-variance-and-the-combination-of-least...,Abstract Missing,"Bias, Variance and the Combination of\nLeast S..."
7238,997,1994,A Real Time Clustering CMOS Neural Engine,NaN,997-a-real-time-clustering-cmos-neural-engine.pdf,Abstract Missing,A Real Time Clustering CMOS\nNeural Engine\nT....
7239,998,1994,Learning direction in global motion: two class...,NaN,998-learning-direction-in-global-motion-two-cl...,Abstract Missing,Learning direction in global motion: two\nclas...
7240,999,1994,Correlation and Interpolation Networks for Rea...,NaN,999-correlation-and-interpolation-networks-for...,Abstract Missing,Correlation and Interpolation Networks for\nRe...

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

# Reduce max_features and adjust n-gram range
cv = CountVectorizer(max_features=6000, ngram_range=(1, 2))

# Create a vocabulary and word count vectors
word_count_vectors = cv.fit_transform(docs)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count_vectors)